Introduce `ENABLE_JSON_LOGGING`
djmaze/resticker pull request #216
Opened 2024-08-30 19:06 UTC by jeankhawand

This change adds the `ENABLE_JSON_LOGGING` option to export restic metadata in JSON format. The goal is to improve accessibility by allowing users to utilize tools like `jq` to process the metadata. This enables users to create external scripts for extracting metadata and sending notifications using `run_commands`.

update doc and include notify script as sample to send backup metadata via apprise

Export `LOG_FILE` and create docker-compose for contributing

- export `LOG_FILE` so it will be available for subprocess executed via `run_commands`
- Add docker-compose.contribute.yml facilitate contributing process
- make `notify` executable and copy it to /usr/local/bin
- notify: update content to only include summary and errors for now. jq was complaining on payload too large when using verbose mode.
- update doc

2024-11-28 13:17 UTC, jeankhawand commented
@djmaze that's will also make it easy to restore snapshots in the futur
![image](https://github.com/user-attachments/assets/f3d44ea2-092d-49c0-be9d-d25e0f69b52b)

2025-01-13 22:45 UTC, djmaze requested changes
Sorry for the late reply.. This looks good to me! But will need a test, see below.

2025-01-13 22:45 UTC, djmaze commented on docker-compose.contributing.yml
> +version: "3.3"
Not sure why you added this file and what the name is exactly about? IMO we can just remove this.

2025-01-13 22:45 UTC, djmaze commented on notify
> +#!/bin/bash
This functionality should also be tested. I will add a test.

2026-07-12 11:41 UTC, closed without merging